#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 02, 2018 02:15:12 AM
#    May 02, 2018 02:42:35 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global algoVar, kernelVar
    algoVar = StringVar()
    algoVar.set(('PCA','Kernel PCA','Incremental PCA'))
    kernelVar = StringVar()
    kernelVar.set(('linear' , 'poly' , 'rbf' , 'sigmoid' , 'cosine' , 'precomputed'))

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import dimreduction
    dimreduction.vp_start_gui()





