#############################################################################
# Generated by PAGE version 4.13
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join D:/ {Sem 8} ml {Final Project} logo.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI Black} -size 18 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI} -size 14 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 623x809+710+61
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "ML GUI"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Machine Learning GUI} 
    vTcl:DefineAlias "$top.lab39" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text Modules/Algorithms 
    vTcl:DefineAlias "$top.lab40" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text Applications 
    vTcl:DefineAlias "$top.lab41" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Data Preprocessing} 
    vTcl:DefineAlias "$top.but53" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Dimensionality Reduction} 
    vTcl:DefineAlias "$top.but54" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but38 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Clustering 
    vTcl:DefineAlias "$top.but38" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but39 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Classification 
    vTcl:DefineAlias "$top.but39" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Regression 
    vTcl:DefineAlias "$top.but40" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but41 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Model Selection} 
    vTcl:DefineAlias "$top.but41" "Button6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but42 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black \
        -image [vTcl:image:get_image [file join D:/ {Sem 8} ml {Final Project} logo.png]] \
        -pady 0 -text Button 
    vTcl:DefineAlias "$top.but42" "Button7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Close 
    vTcl:DefineAlias "$top.but43" "Button8" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} \
        -text {Developed By:
Naman Kasliwal
Chiranjiv Sen
} 
    vTcl:DefineAlias "$top.lab44" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} \
        -text {Transforming input data such as text for
use with machine learning algorithms} 
    vTcl:DefineAlias "$top.lab45" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Visualization, Increased efficiency} 
    vTcl:DefineAlias "$top.lab46" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} \
        -text {Customer segmentation,
Grouping experiment outcomes} 
    vTcl:DefineAlias "$top.lab47" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Spam detection, Image recognition} 
    vTcl:DefineAlias "$top.lab48" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Drug response, Stock prices} 
    vTcl:DefineAlias "$top.lab49" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Improved accuracy via parameter tuning} 
    vTcl:DefineAlias "$top.lab50" "Label9" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab39 \
        -in $top -x 140 -y 10 -width 331 -relwidth 0 -height 57 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 80 -y 90 -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 330 -y 90 -width 217 -height 37 -anchor nw \
        -bordermode inside 
    place $top.but53 \
        -in $top -x 120 -y 150 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 100 -y 200 -anchor nw -bordermode ignore 
    place $top.but38 \
        -in $top -x 150 -y 250 -anchor nw -bordermode ignore 
    place $top.but39 \
        -in $top -x 140 -y 300 -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 150 -y 350 -anchor nw -bordermode ignore 
    place $top.but41 \
        -in $top -x 120 -y 400 -width 136 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but42 \
        -in $top -x 60 -y 480 -width 486 -relwidth 0 -height 196 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 80 -y 720 -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 420 -y 700 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 300 -y 140 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 320 -y 200 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 330 -y 240 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 320 -y 300 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 350 -y 350 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 310 -y 400 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

