#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 01, 2018 10:11:05 PM

import sys
import tkinter.messagebox as tkMessageBox
import dataprocess
import dimreduction
import clustering
import classification
import modelselect
import tkinter.messagebox as tkMessageBox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import mlgui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = ML_GUI (root)
    mlgui_support.init(root, top)
    root.mainloop()

w = None
def create_ML_GUI(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = ML_GUI (w)
    mlgui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ML_GUI():
    global w
    w.destroy()
    w = None


class ML_GUI:
    
    def dataProcess(self):
        self.dataprocess = dataprocess.create_Data_Preprocessing(root)
    
    def dimReduction(self):
        self.dimreduction = dimreduction.create_Dimensionality_Reduction(root)
    
    def clustering(self):
        self.clustering = clustering.create_Clustering(root)
        
    def regression(self):
        self.clustering = tkMessageBox.showinfo("Alert", "Algorithms for regression will be added later.")
    
    def classification(self):
        self.classification = classification.create_Classification(root)
    
    def modelselect(self):
        self.modelselect = modelselect.create_Model_Selection(root)
        
    def cancelGUI(self):
        msg=tkMessageBox.askyesno("Exit", "Are you sure?");
        if(msg):
            root.destroy()
            
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 18 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("623x809+710+61")
        top.title("ML GUI")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.22, rely=0.01, height=57, width=331)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Machine Learning GUI''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.13, rely=0.11, height=37, width=217)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Modules/Algorithms''')

        self.Label2_1 = Label(top)
        self.Label2_1.place(relx=0.53, rely=0.11, height=37, width=217)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font9)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Applications''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.19, rely=0.19, height=33, width=140)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Data Preprocessing''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.16, rely=0.25, height=33, width=182)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Dimensionality Reduction''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.24, rely=0.31, height=33, width=78)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Clustering''')

        self.Button4 = Button(top)
        self.Button4.place(relx=0.22, rely=0.37, height=33, width=99)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Classification''')

        self.Button5 = Button(top)
        self.Button5.place(relx=0.24, rely=0.43, height=33, width=84)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Regression''')

        self.Button6 = Button(top)
        self.Button6.place(relx=0.19, rely=0.49, height=33, width=136)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Model Selection''')
        self.Button6.configure(width=136)

        self.Button7 = Button(top)
        self.Button7.place(relx=0.1, rely=0.59, height=196, width=486)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self._img1 = PhotoImage(file="./logo.png")
        self.Button7.configure(image=self._img1)
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''Button''')
        self.Button7.configure(width=486)

        self.Button8 = Button(top)
        self.Button8.place(relx=0.13, rely=0.89, height=33, width=48)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''Close''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.67, rely=0.87, height=86, width=112)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Developed By:
Naman Kasliwal''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.48, rely=0.17, height=46, width=269)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Transforming input data such as text for
use with machine learning algorithms''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.51, rely=0.25, height=26, width=227)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Visualization, Increased efficiency''')

        self.Label6 = Label(top)
        self.Label6.place(relx=0.53, rely=0.3, height=46, width=216)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Customer segmentation,
Grouping experiment outcomes''')

        self.Label7 = Label(top)
        self.Label7.place(relx=0.51, rely=0.37, height=26, width=240)
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Spam detection, Image recognition''')

        self.Label8 = Label(top)
        self.Label8.place(relx=0.56, rely=0.43, height=26, width=188)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''Drug response, Stock prices''')

        self.Label9 = Label(top)
        self.Label9.place(relx=0.5, rely=0.49, height=26, width=273)
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''Improved accuracy via parameter tuning''')

        self.Button8.configure(command=self.cancelGUI)
        self.Button1.configure(command=self.dataProcess)
        self.Button2.configure(command=self.dimReduction)
        self.Button3.configure(command=self.clustering)
        self.Button4.configure(command=self.classification)
        self.Button5.configure(command=self.regression)
        self.Button6.configure(command=self.modelselect)
        
        


if __name__ == '__main__':
    vp_start_gui()



